
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 13 18:38:51 CEST 2015
//----------------------------------------------------

package compiler.tools;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int OPPLUS = 4;
  public static final int IDF = 21;
  public static final int SYMECRIRE = 18;
  public static final int OPMOINS = 5;
  public static final int EGAL = 19;
  public static final int OPINF = 10;
  public static final int PARO = 11;
  public static final int SYMLIRE = 17;
  public static final int STATUS = 15;
  public static final int PARF = 12;
  public static final int VIRGULE = 20;
  public static final int POINTVIRGULE = 2;
  public static final int OPMULT = 6;
  public static final int TYPE = 16;
  public static final int NOMBRE = 3;
  public static final int EOF = 0;
  public static final int SYMCLASSE = 13;
  public static final int error = 1;
  public static final int OPDIFF = 7;
  public static final int OPSUP = 9;
  public static final int FIN = 14;
  public static final int CSTECHAINE = 22;
  public static final int OPEGAL = 8;
}

