
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 10 16:21:50 CEST 2015
//----------------------------------------------------

package compiler.tools;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int OPDIFF = 7;
  public static final int OPMOINS = 5;
  public static final int OPSUP = 9;
  public static final int PARO = 11;
  public static final int POINTVIRGULE = 2;
  public static final int EOF = 0;
  public static final int OPMULT = 6;
  public static final int PARF = 12;
  public static final int error = 1;
  public static final int OPPLUS = 4;
  public static final int OPEGAL = 8;
  public static final int NOMBRE = 3;
  public static final int OPINF = 10;
}

